apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeting2-api
  namespace: prod
  labels:
    app: budgeting2-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: budgeting2-api
  template:
    metadata:
      labels:
        app: budgeting2-api
    spec:
      containers:
      - name: api
        image: nas.malfin.com:10100/budgeting2-api:GIT_SHORT_HASH
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "2"
          limits:
            memory: "256Mi"
            cpu: "2"
        envFrom:
        - secretRef:
            name: budgeting2-api-secret
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

