apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budgeting2-api-storage
  namespace: prod
  labels:
    app: budgeting2-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

