apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeting2-ui
  namespace: prod
  labels:
    app: budgeting2-ui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: budgeting2-ui
  template:
    metadata:
      labels:
        app: budgeting2-ui
    spec:
      containers:
      - name: ui
        image: nas.malfin.com:10100/budgeting2-ui:GIT_SHORT_HASH
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "2"
          limits:
            memory: "64Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

