package com.griffin.budgeting.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF1B6D2F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F5A8)
val md_theme_light_onPrimaryContainer = Color(0xFF002108)
val md_theme_light_secondary = Color(0xFF516350)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E8D0)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1F11)
val md_theme_light_tertiary = Color(0xFF39656C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBDEBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF7)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF89D88E)
val md_theme_dark_onPrimary = Color(0xFF003912)
val md_theme_dark_primaryContainer = Color(0xFF00531F)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F5A8)
val md_theme_dark_secondary = Color(0xFFB8CCB5)
val md_theme_dark_onSecondary = Color(0xFF243425)
val md_theme_dark_secondaryContainer = Color(0xFF3A4B3A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E8D0)
val md_theme_dark_tertiary = Color(0xFFA2CED6)
val md_theme_dark_onTertiary = Color(0xFF01363D)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D54)
val md_theme_dark_onTertiaryContainer = Color(0xFFBDEBF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DD)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_outlineVariant = Color(0xFF424940)

// Semantic colors for the app
val IncomeGreen = Color(0xFF4CAF50)
val ExpenseRed = Color(0xFFE53935)
val TransferBlue = Color(0xFF1E88E5)
val PositiveChange = Color(0xFF2E7D32)
val NegativeChange = Color(0xFFC62828)

// Premium dark theme colors
val DarkBackground = Color(0xFF0A0E14)
val DarkSurface = Color(0xFF111820)
val DarkSurfaceElevated = Color(0xFF1A2230)
val DarkSurfaceBright = Color(0xFF232D3F)
val AccentCyan = Color(0xFF00D9FF)
val AccentPurple = Color(0xFF8B5CF6)
val AccentGold = Color(0xFFF5A623)
val PremiumGreen = Color(0xFF34D399)
val PremiumRed = Color(0xFFFB7185)
val TextPrimary = Color(0xFFF1F5F9)
val TextSecondary = Color(0xFF94A3B8)
val TextTertiary = Color(0xFF64748B)
val GlassBorder = Color(0x1AFFFFFF) // 10% alpha
val GlassOverlay = Color(0x0DFFFFFF) // 5% alpha
