json.id plaid_account.id
json.plaid_mask plaid_account.plaid_mask
json.plaid_official_name plaid_account.plaid_official_name
json.plaid_type plaid_account.plaid_type
json.plaid_subtype plaid_account.plaid_subtype
json.nickname plaid_account.nickname
json.createdAt plaid_account.created_at
json.updatedAt plaid_account.updated_at
